builds:
- id: "kflex"
  main: ./cmd/kflex
  binary: bin/kflex
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  - ppc64le
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
archives:
- id: kflex
  builds:
  - kflex
release:
  draft: true
  prerelease: auto
  mode: keep-existing