builds:
- id: "kflex"
  main: ./cmd/kflex
  binary: bin/kflex
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  - LDFLAGS=-X k8s.io/client-go/pkg/version.gitCommit=d5b7f94 -X k8s.io/client-go/pkg/version.gitTreeState=clean -X k8s.io/client-go/pkg/version.gitVersion=+kcp-v0.1.0 -X k8s.io/client-go/pkg/version.gitMajor= -X k8s.io/client-go/pkg/version.gitMinor= -X k8s.io/client-go/pkg/version.buildDate=2023-06-12T01:53:46Z -X k8s.io/component-base/version.gitCommit=d5b7f94 -X k8s.io/component-base/version.gitTreeState=clean -X k8s.io/component-base/version.gitVersion=+kcp-v0.1.0 -X k8s.io/component-base/version.gitMajor= -X k8s.io/component-base/version.gitMinor= -X k8s.io/component-base/version.buildDate=2023-06-12T01:53:46Z -extldflags -static
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
  - LDFLAGS=-X k8s.io/client-go/pkg/version.gitCommit=d5b7f94 -X k8s.io/client-go/pkg/version.gitTreeState=clean -X k8s.io/client-go/pkg/version.gitVersion=+kcp-v0.1.0 -X k8s.io/client-go/pkg/version.gitMajor= -X k8s.io/client-go/pkg/version.gitMinor= -X k8s.io/client-go/pkg/version.buildDate=2023-06-12T01:53:46Z -X k8s.io/component-base/version.gitCommit=d5b7f94 -X k8s.io/component-base/version.gitTreeState=clean -X k8s.io/component-base/version.gitVersion=+kcp-v0.1.0 -X k8s.io/component-base/version.gitMajor= -X k8s.io/component-base/version.gitMinor= -X k8s.io/component-base/version.buildDate=2023-06-12T01:53:46Z -extldflags -static
- id: "manager"
  main: ./cmd/manager
  binary: bin/manager
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0  
  - LDFLAGS=-X k8s.io/client-go/pkg/version.gitCommit=d5b7f94 -X k8s.io/client-go/pkg/version.gitTreeState=clean -X k8s.io/client-go/pkg/version.gitVersion=+kcp-v0.1.0 -X k8s.io/client-go/pkg/version.gitMajor= -X k8s.io/client-go/pkg/version.gitMinor= -X k8s.io/client-go/pkg/version.buildDate=2023-06-12T01:53:46Z -X k8s.io/component-base/version.gitCommit=d5b7f94 -X k8s.io/component-base/version.gitTreeState=clean -X k8s.io/component-base/version.gitVersion=+kcp-v0.1.0 -X k8s.io/component-base/version.gitMajor= -X k8s.io/component-base/version.gitMinor= -X k8s.io/component-base/version.buildDate=2023-06-12T01:53:46Z -extldflags -static
archives:
- id: kflex
  builds:
  - kflex
kos:           
  - repository: ghcr.io/kubestellar/kubeflex
    main: ./cmd/manager
    build: manager
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    ldflags:
    - "{{ .Env.LDFLAGS }}"
    platforms:
    - linux/amd64
    - linux/arm64
    env:
    - CGO_ENABLED=0
    - LDFLAGS=-X k8s.io/client-go/pkg/version.gitCommit=d5b7f94 -X k8s.io/client-go/pkg/version.gitTreeState=clean -X k8s.io/client-go/pkg/version.gitVersion=+kcp-v0.1.0 -X k8s.io/client-go/pkg/version.gitMajor= -X k8s.io/client-go/pkg/version.gitMinor= -X k8s.io/client-go/pkg/version.buildDate=2023-06-12T01:53:46Z -X k8s.io/component-base/version.gitCommit=d5b7f94 -X k8s.io/component-base/version.gitTreeState=clean -X k8s.io/component-base/version.gitVersion=+kcp-v0.1.0 -X k8s.io/component-base/version.gitMajor= -X k8s.io/component-base/version.gitMinor= -X k8s.io/component-base/version.buildDate=2023-06-12T01:53:46Z -extldflags -static
release:
  draft: false
  prerelease: auto
  mode: keep-existing

