presubmits:
  # - name: pull-kubestellar-kubeflex-verify
  #   always_run: true
  #   decorate: true
  #   clone_uri: "https://github.com/kubestellar/kubeflex"
  #   spec:
  #     containers:
  #       - image: ghcr.io/kubestellar/infra/build:1.24.2-1
  #         command:
  #           - make
  #           - verify-boilerplate
  #           - verify-codegen
  #           - verify-go-versions
  #           - verify-imports
  #           - verify-modules
  #         resources:
  #           requests:
  #             memory: 1Gi
  #             cpu: 1

  # - name: pull-kubestellar-kubeflex-lint
  #   always_run: true
  #   decorate: true
  #   clone_uri: "https://github.com/kubestellar/kubeflex"
  #   spec:
  #     containers:
  #       - image: ghcr.io/kubestellar/infra/build:1.24.2-1
  #         command:
  #           - make
  #           - lint
  #         resources:
  #           requests:
  #             memory: 4Gi
  #             cpu: 2

  - name: pull-kubestellar-kubeflex-test-unit
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/kubeflex"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kubestellar/infra/build:1.24.2-1
          command:
            - make
            - test
          env:
            - name: USE_GOTESTSUM
              value: '1'
          resources:
            requests:
              memory: 4Gi
              cpu: 2
