# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeflex < Formula
  desc ""
  homepage "https://github.com/kubestellar/kubeflex"
  version "0.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/kubeflex/releases/download/v0.8.1/kubeflex_0.8.1_darwin_amd64.tar.gz"
      sha256 "1ba5938ad65cb06c1adcf878b9d02abd9a3e68feeba599ab7d81908f06e426d8"

      def install
        bin.install "bin/kflex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/kubeflex/releases/download/v0.8.1/kubeflex_0.8.1_darwin_arm64.tar.gz"
      sha256 "b304357f0fdbc49fa92c0fd7ae43f158efbdb4a4de660e8f6a6b0fdf15c7fbbd"

      def install
        bin.install "bin/kflex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubestellar/kubeflex/releases/download/v0.8.1/kubeflex_0.8.1_linux_amd64.tar.gz"
        sha256 "441cebb3a44667fb99f2bb4a5d68d60156248b0425a98d51f0bcfb2033169151"

        def install
          bin.install "bin/kflex"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubestellar/kubeflex/releases/download/v0.8.1/kubeflex_0.8.1_linux_arm64.tar.gz"
        sha256 "3b4ae6b42837e251d3dcfff0cebd9d5a5bef7acbbb21faa360ea0717b942dcca"

        def install
          bin.install "bin/kflex"
        end
      end
    end
  end
end
