# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeflex < Formula
  desc ""
  homepage "https://github.com/kubestellar/kubeflex"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/kubeflex/releases/download/v0.8.0/kubeflex_0.8.0_darwin_amd64.tar.gz"
      sha256 "7d2323eb7a6796e749900f79627496ae80bce4f04be433db64737162096f2786"

      def install
        bin.install "bin/kflex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/kubeflex/releases/download/v0.8.0/kubeflex_0.8.0_darwin_arm64.tar.gz"
      sha256 "671e8613c17aa9e78df3edbca23a9e80e561b902769d2c5e494960397f988feb"

      def install
        bin.install "bin/kflex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubestellar/kubeflex/releases/download/v0.8.0/kubeflex_0.8.0_linux_amd64.tar.gz"
        sha256 "a2d3697586ac3b70cf4b123fe9241f0fbd29f4d8dadf1b0272a4d07fb345fa2b"

        def install
          bin.install "bin/kflex"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubestellar/kubeflex/releases/download/v0.8.0/kubeflex_0.8.0_linux_arm64.tar.gz"
        sha256 "0ac71010b288895c1a2a4164c19224c5032387d34269222ea02c929310a94d2f"

        def install
          bin.install "bin/kflex"
        end
      end
    end
  end
end
