name: goreleaser

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v4
      with:
        go-version: v1.19
    - name: Delete non-semver tags
      run: 'git tag -d $(git tag -l | grep -v "^v")'
    - name: Set LDFLAGS
      run: echo LDFLAGS="$(make ldflags)" >> $GITHUB_ENV
    - name: Run GoReleaser on tag
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --timeout 60m --clean --ko-token ${{ secrets.KO_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

