name: CreateReleaseBranch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release branch (e.g. 0.1)'
        required: true

jobs:
  create-relesea-branch:
    runs-on: ubuntu-22.04

    steps:
      - name:
        uses: peterjgrainger/action-create-branch@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release-${{ github.event.inputs.branch }}
