name: E2E test

on:
  workflow_call:
   inputs:
    release:
      description: 'Kubeflex release to test (e.g. latest or v0.5.1)'
      required: false
      type: string
  workflow_dispatch:
   inputs:
    release:
      description: 'Kubeflex release to test (e.g. latest or v0.5.1)'
      required: false
      type: string
  pull_request:
    branches:
      - main
      - "lxf/**"
  push:
    branches:
      - main
      - "lxf/**"
    tags:
      - "v*"

jobs:
  test-controlplane-lifecycle-management:
    name: E2E test on ${{ matrix.cluster-type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster-type: [kind, k3d]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version: v1.24.5
          cache: true

      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d

      - name: Install kubectl
        uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d
        id: install

      - name: Install k3d
        if: matrix.cluster-type == 'k3d'
        run: bash <(curl -sSL https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh)

      - name: Run test
        run: |
          if [ -n "${{ inputs.release }}" ]; then
             test/e2e/run.sh --cluster-type ${{ matrix.cluster-type }} --release ${{ inputs.release }}
          else
             test/e2e/run.sh --cluster-type ${{ matrix.cluster-type }}
          fi

      - name: Examine GitHub rate limit
        run: curl https://api.github.com/rate_limit

      - name: Show kubeconfig contexts
        if: always()
        run: kubectl config get-contexts

      - name: Show running components of KubeFlex
        if: always()
        run: kubectl --context ${{ matrix.cluster-type }}-kubeflex -n kubeflex-system get all

      - name: Show logs of the KubeFlex controller manager
        if: always()
        run: kubectl --context ${{ matrix.cluster-type }}-kubeflex -n kubeflex-system logs deploy/kubeflex-controller-manager

      - name: Show logs of the shared Postgres DB
        if: always()
        run: kubectl --context ${{ matrix.cluster-type }}-kubeflex -n kubeflex-system logs sts/postgres-postgresql

      - name: Show logs of the KubeFlex operator
        if: always()
        run: kubectl --context ${{ matrix.cluster-type }}-kubeflex -n kubeflex-system logs job/kubeflex-operator
