name: E2E test

on:
  workflow_call:
   inputs:
    release:
      description: 'Kubeflex release to test (e.g. latest or v0.5.1)'
      required: false
      type: string
  workflow_dispatch:
   inputs:
    release:
      description: 'Kubeflex release to test (e.g. latest or v0.5.1)'
      required: false
      type: string
  pull_request:
    branches:
      - main
      - "lxf/**"
  push:
    branches:
      - main
      - "lxf/**"
    tags:
      - "v*"

jobs:
  test-controlplane-lifecycle-management:
    name: E2E test on ${{ matrix.cluster-type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster-type: [kind, k3d]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version: v1.24.5
          cache: true

      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445

      - name: Install kubectl
        uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d
        id: install

      - name: Install k3d
        if: matrix.cluster-type == 'k3d'
        run: bash <(curl -sSL https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh)

      - name: Run test
        run: |
          if [ -n "${{ inputs.release }}" ]; then
             test/e2e/run.sh --cluster-type ${{ matrix.cluster-type }} --release ${{ inputs.release }}
          else
             test/e2e/run.sh --cluster-type ${{ matrix.cluster-type }}
          fi

      - name: Examine GitHub rate limit
        if: always()
        run: curl https://api.github.com/rate_limit

      - name: Show kubeconfig contexts
        if: always()
        run: kubectl config get-contexts

      - name: Dump ControlPlane objects
        if: always()
        run: kubectl --context ${{ matrix.cluster-type }}-kubeflex get controlplanes -o yaml

      - name: Dump PostCreateHooks
        if: always()
        run: kubectl --context ${{ matrix.cluster-type }}-kubeflex get postcreatehooks -o yaml

      - name: List all objects of category all
        if: always()
        run: kubectl --context ${{ matrix.cluster-type }}-kubeflex get -A all

      - name: Dump all Job objects
        if: always()
        run: kubectl --context ${{ matrix.cluster-type }}-kubeflex get -A jobs -o yaml

      - name: Dump all Pod objects
        if: always()
        run: kubectl --context ${{ matrix.cluster-type }}-kubeflex get -A pods -o yaml

      - name: Dump all Kubernetes event objects
        if: always()
        run: kubectl --context ${{ matrix.cluster-type }}-kubeflex get -A events --sort-by='.lastTimestamp'

      - name: Dump all Service objects
        if: always()
        run: kubectl --context ${{ matrix.cluster-type }}-kubeflex get -A services -o yaml

      - name: Dump all EndpointSlice objects
        if: always()
        run: kubectl --context ${{ matrix.cluster-type }}-kubeflex get -A endpointslices -o yaml

      - name: Dump kubeflex Pod logs
        if: always()
        run: |
          for ns in $(kubectl --context ${{ matrix.cluster-type }}-kubeflex get ns -o name | sed s:namespace/:: | grep -e '-system$' | grep -v kube-system); do
            for pod in $(kubectl --context ${{ matrix.cluster-type }}-kubeflex -n "$ns" get pods -o 'jsonpath={.items[*].metadata.name} ' || true) ; do
              containers=$(kubectl --context ${{ matrix.cluster-type }}-kubeflex -n "$ns" get pod "$pod" -o 'jsonpath={.spec.containers[*].name}' || true)
              for container in $containers ; do
                echo ""
                echo "=== Previous log of $ns/$pod (container: $container) ==="
                kubectl --context ${{ matrix.cluster-type }}-kubeflex -n "$ns" logs "$pod" -c "$container" --previous || true
                echo ""
                echo "=== Log of $ns/$pod (container: $container) ==="
                kubectl --context ${{ matrix.cluster-type }}-kubeflex -n "$ns" logs "$pod" -c "$container" || true
              done
            done
          done
